CREATE TABLE [dbo].[SnOPDemandProductHierarchyCDC] (
    [SnOPDemandProductId]            INT           NOT NULL,
    [SnOPDemandProductCd]            VARCHAR (100) NULL,
    [SnOPDemandProductNm]            VARCHAR (100) NULL,
    [MarketingCodeNm]                VARCHAR (100) NULL,
    [IsActive]                       BIT           NOT NULL,
    [MarketingCd]                    VARCHAR (100) NULL,
    [SnOPBrandGroupNm]               VARCHAR (100) NULL,
    [SnOPComputeArchitectureGroupNm] VARCHAR (100) NULL,
    [SnOPFunctionalCoreGroupNm]      VARCHAR (100) NULL,
    [SnOPGraphicsTierCd]             VARCHAR (100) NULL,
    [SnOPMarketSwimlaneNm]           VARCHAR (100) NULL,
    [SnOPMarketSwimlaneGroupNm]      VARCHAR (100) NULL,
    [SnOPPerformanceClassNm]         VARCHAR (100) NULL,
    [SnOPPackageCd]                  VARCHAR (100) NULL,
    [SnOPPackageFunctionalTypeNm]    VARCHAR (100) NULL,
    [SnOPProcessNm]                  VARCHAR (100) NULL,
    [SnOPProcessNodeNm]              VARCHAR (100) NULL,
    [ProductGenerationSeriesCd]      VARCHAR (100) NULL,
    [SnOPProductTypeNm]              VARCHAR (100) NULL,
    [DesignBusinessNm]               VARCHAR (100) NULL,
    [DesignNm]                       VARCHAR (255) NULL,
    [CreatedOn]                      DATETIME      NOT NULL,
    [CreatedBy]                      VARCHAR (25)  NOT NULL,
    [OperationDsc]                   VARCHAR (50)  NULL,
    [CDCDate]                        DATETIME      NOT NULL,
    CONSTRAINT [PK_DemandProductHierarchyCDC] PRIMARY KEY CLUSTERED ([SnOPDemandProductId] ASC, [CDCDate] ASC)
);

