CREATE TABLE [dbo].[StgItemPrqMilestone] (
    [BulkId]                           BIGINT         NULL,
    [RowId]                            INT            NULL,
    [InsDtm]                           DATETIME       NULL,
    [InstcNm]                          NVARCHAR (255) NULL,
    [SpeedId]                          INT            NULL,
    [Project]                          NVARCHAR (255) NULL,
    [MilestoneUid]                     NVARCHAR (100) NULL,
    [Milestone]                        NVARCHAR (100) NULL,
    [MilestoneBase]                    NVARCHAR (255) NULL,
    [PlcOrder]                         INT            NULL,
    [Importance]                       INT            NULL,
    [DriveTo]                          DATETIME       NULL,
    [DriveToWwyy]                      NVARCHAR (13)  NULL,
    [DriveToLastUpdate]                DATETIME       NULL,
    [DriveToLastUpdatedByIdsid]        NVARCHAR (50)  NULL,
    [DriveToLastUpdatedByWwid]         NVARCHAR (8)   NULL,
    [Por]                              DATETIME       NULL,
    [PorWwyy]                          NVARCHAR (13)  NULL,
    [PorQuarter]                       NVARCHAR (9)   NULL,
    [PorLastUpdate]                    DATETIME       NULL,
    [PorLastUpdatedByIdsid]            NVARCHAR (50)  NULL,
    [PorLastUpdatedByWwid]             NVARCHAR (8)   NULL,
    [Trend]                            DATETIME       NULL,
    [TrendWwyy]                        NVARCHAR (13)  NULL,
    [TrendLastUpdate]                  DATETIME       NULL,
    [TrendLastUpdatedByIdsid]          NVARCHAR (50)  NULL,
    [TrendLastUpdatedByWwid]           NVARCHAR (8)   NULL,
    [ActualFinish]                     DATETIME       NULL,
    [ActualFinishWwyy]                 NVARCHAR (13)  NULL,
    [ActualFinishLastUpdate]           DATETIME       NULL,
    [ActualFinishLastUpdatedByIdsid]   NVARCHAR (50)  NULL,
    [ActualFinishLastUpdatedByWwid]    NVARCHAR (8)   NULL,
    [SteppingName]                     NVARCHAR (100) NULL,
    [Enabled]                          BIT            NULL,
    [RbeLastUpdate]                    DATETIME       NULL,
    [RbeLastUpdatedByIdsid]            NVARCHAR (50)  NULL,
    [RbeLastUpdatedByWwid]             NVARCHAR (8)   NULL,
    [Rbe]                              BIGINT         NULL,
    [OriginalCommit]                   DATETIME       NULL,
    [OriginalCommitWwyy]               NVARCHAR (13)  NULL,
    [OriginalCommitLastUpdate]         DATETIME       NULL,
    [OriginalCommitLastUpdatedByIdsid] NVARCHAR (50)  NULL,
    [OriginalCommitLastUpdatedByWwid]  NVARCHAR (10)  NULL
);

