CREATE TABLE [dbo].[StgProductHierarchy] (
    [HierarchyLevelId]               NVARCHAR (100)  NULL,
    [ProductNodeID]                  INT             NULL,
    [SnOPDemandProductId]            INT             NULL,
    [SnOPSupplyProductId]            INT             NULL,
    [FinishedGoodItemId]             NVARCHAR (100)  NULL,
    [ProductGenerationSeriesCd]      NVARCHAR (100)  NULL,
    [SnOPSupplyProductNm]            NVARCHAR (100)  NULL,
    [SnOPSupplyProductCd]            NVARCHAR (100)  NULL,
    [SnOPDemandProductNm]            NVARCHAR (1000) NULL,
    [SnOPBrandGroupNm]               NVARCHAR (100)  NULL,
    [MarketingCodeNm]                NVARCHAR (100)  NULL,
    [MarketingCd]                    NVARCHAR (100)  NULL,
    [SnOPDemandProductCd]            NVARCHAR (100)  NULL,
    [SnOPFunctionalCoreGroupNm]      NVARCHAR (100)  NULL,
    [SnOPPackageCd]                  NVARCHAR (100)  NULL,
    [SnOPComputeArchitectureGroupNm] NVARCHAR (100)  NULL,
    [SnOPMarketSwimlaneNm]           NVARCHAR (100)  NULL,
    [SnOPGraphicsTierCd]             NVARCHAR (100)  NULL,
    [SnOPPerformanceClassNm]         NVARCHAR (100)  NULL,
    [SnOPProductTypeNm]              NVARCHAR (100)  NULL,
    [SnOPPackageFunctionalTypeNm]    NVARCHAR (100)  NULL,
    [SnOPMarketSwimlaneGroupNm]      NVARCHAR (100)  NULL,
    [SnOPProcessNm]                  NVARCHAR (100)  NULL,
    [SnOPProcessNodeNm]              NVARCHAR (100)  NULL,
    [ActiveInd]                      NVARCHAR (1)    NULL,
    [DesignBusinessNm]               NVARCHAR (100)  NULL,
    [CreateDtm]                      DATETIME        NULL,
    [CreateUserNm]                   NVARCHAR (100)  NULL,
    [LastUpdateUserNm]               NVARCHAR (100)  NULL,
    [LastUpdateUserDtm]              DATETIME        NULL,
    [SpecCd]                         NVARCHAR (10)   NULL,
    [SnOPWayness]                    NVARCHAR (30)   NULL,
    [DataCenterDemandInd]            NVARCHAR (5)    NULL,
    [SnOPWaferFOCd]                  NVARCHAR (30)   NULL,
    [SnOPBoardFormFactorCd]          NVARCHAR (30)   NULL,
    [PlanningSupplyPackageVariantId] NVARCHAR (30)   NULL,
    [FinishedGoodCurrentBusinessNm]  NVARCHAR (100)  NULL
);

