CREATE TABLE [dbo].[StgSopFiscalCalendar] (
    [SourceApplicationName]            VARCHAR (25)   NOT NULL,
    [SourceVersionId]                  INT            NOT NULL,
    [Fiscal Calendar Identifier]       INT            NULL,
    [Start Date]                       NVARCHAR (10)  NULL,
    [LastMonthOfFiscalQuarterNbr]      NVARCHAR (3)   NULL,
    [FiscalQuarterNbr]                 NVARCHAR (1)   NULL,
    [FiscalQuarterWorkweekNbr]         NVARCHAR (5)   NULL,
    [RelativeFiscalMonthsFromTodayNbr] INT            NULL,
    [RelativeQuarter]                  INT            NULL,
    [RelativeWorkweek]                 INT            NULL,
    [RelativeYear]                     INT            NULL,
    [WorkWeekNm]                       NVARCHAR (4)   NULL,
    [WorkWeekNbr]                      NVARCHAR (3)   NULL,
    [FiscalAbbreviatedMonthYearNm]     NVARCHAR (20)  NULL,
    [FiscalMonthNm]                    NVARCHAR (5)   NULL,
    [FiscalMonthNbr]                   NVARCHAR (2)   NULL,
    [Year]                             NVARCHAR (4)   NULL,
    [Fiscal Year Quarter Name]         NVARCHAR (6)   NULL,
    [FiscalYearQuarterNbr]             NVARCHAR (6)   NULL,
    [Workweek]                         NVARCHAR (6)   NULL,
    [WeeksInFiscalMonthCnt]            BIGINT         NULL,
    [WeeksInFiscalQuarterCnt]          BIGINT         NULL,
    [FiscalPeriodEndDateTxt]           NVARCHAR (10)  NULL,
    [RelativeDaysFromTodayNbr]         INT            NULL,
    [FiscalMonthWorkweekNbr]           NVARCHAR (5)   NULL,
    [FiscalQuarterMonthNbr]            NVARCHAR (1)   NULL,
    [CalendarCharDt]                   NVARCHAR (8)   NULL,
    [FiscalYearMonthNm]                NVARCHAR (MAX) NULL,
    [FiscalYearMonthNbr]               NVARCHAR (6)   NULL,
    [SourceNm]                         NVARCHAR (15)  NULL,
    [LastYearMonthOfFiscalQuarterNbr]  NVARCHAR (255) NULL,
    [CreatedOn]                        DATETIME       DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                        VARCHAR (25)   DEFAULT (original_login()) NOT NULL
);

