CREATE TABLE [dbo].[SupplyDistribution#DistInfo] (
    [PlanningMonth]                 INT          NOT NULL,
    [SourceApplicationId]           INT          NOT NULL,
    [SourceVersionId]               INT          NOT NULL,
    [SupplyParameterId]             INT          NOT NULL,
    [SnOPDemandProductId]           INT          NOT NULL,
    [YearWw]                        INT          NOT NULL,
    [ProfitCenterCd]                INT          NOT NULL,
    [Demand]                        FLOAT (53)   NULL,
    [Boh]                           FLOAT (53)   NULL,
    [OneWoi]                        FLOAT (53)   NULL,
    [DistCategoryId]                INT          NULL,
    [Priority]                      INT          NULL,
    [PcWoi]                         FLOAT (53)   NULL,
    [ProdWoi]                       FLOAT (53)   NULL,
    [OffTopTargetInvQty]            FLOAT (53)   NULL,
    [ProdTargetInvQty]              FLOAT (53)   NULL,
    [OffTopTargetBuildQty]          FLOAT (53)   NULL,
    [ProdTargetBuildQty]            FLOAT (53)   NULL,
    [FairSharePercent]              FLOAT (53)   NULL,
    [AllPcPercent]                  FLOAT (53)   NULL,
    [AllPcPercentForNegativeSupply] FLOAT (53)   NULL,
    [DistCnt]                       INT          DEFAULT ((0)) NULL,
    [IsTargetInvCovered]            BIT          DEFAULT ((0)) NULL,
    [CreatedOn]                     DATETIME     DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                     VARCHAR (25) DEFAULT (original_login()) NOT NULL,
    PRIMARY KEY CLUSTERED ([PlanningMonth] ASC, [SupplyParameterId] ASC, [SourceApplicationId] ASC, [SourceVersionId] ASC, [SnOPDemandProductId] ASC, [YearWw] ASC, [ProfitCenterCd] ASC)
);

