CREATE TABLE [sop].[StgIqmExcess] (
    [ProfitCenterPct]            FLOAT (53)       NULL,
    [NonBonusableCum]            DECIMAL (38, 10) NULL,
    [NonBonusableDiscreteExcess] FLOAT (53)       NULL,
    [ExcessToMpsInvTargetCum]    FLOAT (53)       NULL,
    [BonusableDiscreteExcess]    FLOAT (53)       NULL,
    [ProfitCenterCd]             INT              NOT NULL,
    [SuperGroupNm]               VARCHAR (100)    NULL,
    [EsdVersionId]               INT              NOT NULL,
    [SourceApplicationName]      VARCHAR (25)     NOT NULL,
    [SourceVersionId]            INT              NOT NULL,
    [ResetWw]                    INT              NOT NULL,
    [WhatIfScenarioName]         VARCHAR (50)     NOT NULL,
    [SdaFamily]                  VARCHAR (50)     NULL,
    [ItemName]                   VARCHAR (50)     NOT NULL,
    [ItemClass]                  VARCHAR (25)     NULL,
    [ItemDescription]            VARCHAR (100)    NULL,
    [SnOPDemandProductId]        INT              NOT NULL,
    [BonusPercent]               FLOAT (53)       NULL,
    [Comments]                   VARCHAR (MAX)    NULL,
    [YearQq]                     INT              NOT NULL,
    [Process]                    VARCHAR (50)     NULL,
    [YearMm]                     INT              NULL,
    [VersionFiscalCalendarId]    INT              NULL,
    [FiscalCalendarId]           INT              NULL,
    [TypeData]                   VARCHAR (25)     NOT NULL,
    [ProfitCenterHierarchyId]    INT              NULL,
    [SvdSourceVersionId]         INT              NOT NULL
);

