CREATE TABLE [sop].[StgTimePeriod] (
    [Fiscal Calendar Identifier]       INT           NULL,
    [Start Date]                       VARCHAR (10)  NULL,
    [LastMonthOfFiscalQuarterNbr]      VARCHAR (3)   NULL,
    [FiscalQuarterNbr]                 VARCHAR (1)   NULL,
    [FiscalQuarterWorkweekNbr]         VARCHAR (5)   NULL,
    [RelativeFiscalMonthsFromTodayNbr] INT           NULL,
    [RelativeQuarter]                  INT           NULL,
    [RelativeWorkweek]                 INT           NULL,
    [RelativeYear]                     INT           NULL,
    [WorkWeekNm]                       VARCHAR (4)   NULL,
    [WorkWeekNbr]                      VARCHAR (3)   NULL,
    [FiscalAbbreviatedMonthYearNm]     VARCHAR (20)  NULL,
    [FiscalMonthNm]                    VARCHAR (5)   NULL,
    [FiscalMonthNbr]                   VARCHAR (2)   NULL,
    [Year]                             VARCHAR (4)   NULL,
    [Fiscal Year Quarter Name]         VARCHAR (6)   NULL,
    [FiscalYearQuarterNbr]             VARCHAR (6)   NULL,
    [Workweek]                         VARCHAR (6)   NULL,
    [WeeksInFiscalMonthCnt]            BIGINT        NULL,
    [WeeksInFiscalQuarterCnt]          BIGINT        NULL,
    [FiscalPeriodEndDateTxt]           VARCHAR (10)  NULL,
    [RelativeDaysFromTodayNbr]         INT           NULL,
    [FiscalMonthWorkweekNbr]           VARCHAR (5)   NULL,
    [FiscalQuarterMonthNbr]            VARCHAR (1)   NULL,
    [CalendarCharDt]                   VARCHAR (8)   NULL,
    [FiscalYearMonthNbr]               VARCHAR (6)   NULL,
    [SourceNm]                         VARCHAR (15)  NULL,
    [LastYearMonthOfFiscalQuarterNbr]  VARCHAR (255) NULL,
    [FiscalYearMonthNm]                VARCHAR (255) NULL,
    [PackageSystemId]                  INT           DEFAULT ([sop].[CONST_PackageSystemId_Dimension]()) NULL,
    [SourceSystemId]                   INT           DEFAULT ([sop].[CONST_SourceSystemId_SapMdg]()) NULL,
    [CreatedOnDtm]                     DATETIME      DEFAULT (getdate()) NOT NULL,
    [CreatedByNm]                      [sysname]     DEFAULT (original_login()) NOT NULL,
    [ModifiedOnDtm]                    DATETIME      DEFAULT (getdate()) NOT NULL,
    [ModifiedByNm]                     [sysname]     DEFAULT (original_login()) NOT NULL
);

