CREATE TABLE [sop].[TimePeriod] (
    [TimePeriodId]                     INT            NOT NULL,
    [TimePeriodDisplayNm]              NVARCHAR (12)  NOT NULL,
    [SourceTimePeriodId]               INT            NOT NULL,
    [StartDt]                          DATE           NULL,
    [EndDt]                            DATE           NULL,
    [LastMonthOfFiscalQuarterNbr]      NVARCHAR (4)   NULL,
    [FiscalQuarterNbr]                 NVARCHAR (2)   NULL,
    [FiscalQuarterWorkweekNbr]         NVARCHAR (5)   NULL,
    [RelativeFiscalMonthsFromTodayNbr] INT            NULL,
    [RelativeQuarterNbr]               INT            NULL,
    [RelativeWorkweekNbr]              INT            NULL,
    [RelativeYearNbr]                  INT            NULL,
    [WorkWeekNm]                       NVARCHAR (8)   NULL,
    [WorkWeekNbr]                      NVARCHAR (6)   NULL,
    [FiscalAbbreviatedMonthYearNm]     NVARCHAR (40)  NULL,
    [FiscalMonthNm]                    NVARCHAR (10)  NULL,
    [FiscalMonthNbr]                   NVARCHAR (4)   NULL,
    [YearNbr]                          NVARCHAR (8)   NULL,
    [FiscalYearQuarterNm]              NVARCHAR (12)  NULL,
    [FiscalYearQuarterNbr]             NVARCHAR (12)  NULL,
    [YearWorkweekNbr]                  NVARCHAR (12)  NULL,
    [WeeksInFiscalMonthCnt]            BIGINT         NULL,
    [WeeksInFiscalQuarterCnt]          BIGINT         NULL,
    [FiscalPeriodEndDateTxt]           NVARCHAR (20)  NULL,
    [RelativeDaysFromTodayNbr]         INT            NULL,
    [FiscalMonthWorkweekNbr]           NVARCHAR (10)  NULL,
    [FiscalQuarterMonthNbr]            NVARCHAR (2)   NULL,
    [CalendarCharDt]                   NVARCHAR (16)  NULL,
    [FiscalYearMonthNm]                NVARCHAR (20)  NULL,
    [FiscalYearMonthNbr]               NVARCHAR (12)  NULL,
    [SourceNm]                         NVARCHAR (30)  NULL,
    [LastYearMonthOfFiscalQuarterNbr]  NVARCHAR (255) NULL,
    [QuarterSequenceNbr]               INT            NULL,
    [MonthSequenceNbr]                 INT            NULL,
    [WorkWeekSequenceNbr]              INT            NULL,
    [SourceSystemId]                   INT            NOT NULL,
    [CreatedOnDtm]                     DATETIME       CONSTRAINT [DF_Time_CreatedOnDtm] DEFAULT (getdate()) NOT NULL,
    [CreatedByNm]                      VARCHAR (25)   CONSTRAINT [DF_Time_CreatedByNm] DEFAULT (original_login()) NOT NULL,
    [ModifiedOnDtm]                    DATETIME       CONSTRAINT [DF_Time_ModifiedOnDtm] DEFAULT (getdate()) NOT NULL,
    [ModifiedByNm]                     VARCHAR (25)   CONSTRAINT [DF_Time_ModifiedByNm] DEFAULT (original_login()) NOT NULL,
    CONSTRAINT [PK_TimePeriod] PRIMARY KEY CLUSTERED ([TimePeriodId] ASC),
    CONSTRAINT [FK_TimePeriod_SourceSystem] FOREIGN KEY ([SourceSystemId]) REFERENCES [sop].[SourceSystem] ([SourceSystemId])
);

