
CREATE PROC [dbo].[UspLoadCustomerHierarchy]

AS
/************************************************************************************
DESCRIPTION: This proc is used to load data from denodo Customer Hierarchy table
*************************************************************************************/
----    Date        User                    Description
----***************************************************************************-
----    2023-06-13  rmiralhx                Initial Release
----*********************************************************************************/
BEGIN
    SET NOCOUNT ON
    DECLARE @BatchId VARCHAR(100) = 'LoadCustomerHierarchy.' + CONVERT(VARCHAR(30), GETDATE(), 121) + '.' + SYSTEM_USER
    DECLARE @EmailMessage VARCHAR(1000) ='LoadCustomerHierarchy Successful'
    DECLARE @Prog VARCHAR(255)
    DECLARE @SourceApplicationName VARCHAR(100) = 'Denodo'


    BEGIN TRY
        --Logging Start
        EXEC dbo.UspAddApplicationLog 'Database', 'Info', 'LoadCustomerHierarchy', 'UspLoadCustomerHierarchy','Load daily data from Customer Hierarchy', 'BEGIN', NULL, @BatchId


        MERGE dbo.SnOPCustomerHierarchy AS TARGET 
        USING (SELECT [CustomerNodeId]
          ,[CustomerGroup]
          ,[SubCustomer]
          ,[CustomerAllocationGroupCd]
          ,[PartyID]
          ,[HostedRegion]
          ,[CustomerType]
          ,[CCGCPUNotebookGroupNm]
          ,[CCGCPUDesktopGroupNm]
          ,[CCGChipsetGroupNm]
          ,[CCGDesktopWorkstationGroupNm]
          ,[CCGMobileCommGrp]
          ,[CCGWifiGrp]
          ,[CCGConnectivityGrp]
          ,[DCGGrp]
          ,[DCGOptaneGrp]
          ,[IOTGGrp]
          ,[CustomerAllocationGroupNm]
          ,[SourceSystem]
          ,[SMGSalesRollup]
          ,[DistributionChannelNm]
          ,[DistributionChannelCd]
          ,[SalesOfficeCd]
          ,[SalesOfficeNm]
          ,[GeographyCd]
          ,[SalesGroupCd]
          ,[SalesGroupNm]
          ,[CustomerNm]
          ,[CustomerClassificationCd]
          ,[CustomerClassificationNm]
          ,[CustomerCountryCd]
          ,[CustomerCountryNm]
          ,[CustomerAggregationLevelOneNm]
          ,[CustomerAggregationLevelTwoNm]
          ,[CustomerAggregationLevelThreeNm]
          ,[SalesOrganizationCd]
          ,[PriceCustomerGroupCd]
          ,[BusinessNameTypeCd]
          ,[BusinessNameTypeNm]
          ,[BusinessNameTypeDsc]
          ,[CustomerBusinessPartyIdTypeNm]
          ,[DirectCustomerRoleCd]
          ,[CustomerCentralArchivalDeleteBlockCd]
          ,[IntelProductGroupCd]
          ,[IntelUltimateBusinessPartyId]
          ,[CustomerCentralOrderBlockCd]
          ,[CustomerCentralBillingBlockCd]
          ,[CustomerCentralDeliveryBlockCd]
          ,[CustomerBusinessRoutingCd]
          ,[CustomerBusinessRoutingNm]
          ,[CustomerCentralDeleteBlockCd]
          ,[HierarchyLevelId]
          ,[SourceName]
          ,[AllCustomerIdentifier]
          ,[SalesAndOperationsPlanningCustomerGroupId]
          ,[SalesAndOperationsPlanningSubCustomerId]
          ,[SalesAndOperationsPlanningCustomerAllocationGroupId]
          ,[SalesAndOperationsPlanningPartyId]
          ,[CustomerBusinessOrganizationNm]
          ,[CustomerSupplyAllocationClassificationCd]
          ,[CustomerSupplyAllocationClassificationNm]
          ,[PartnerCustomerBusinessPartyId]
          ,[CustomerRelationshipFunctionalRoleCd]
          ,[CustomerRelationshipFunctionalRoleNm]
          ,[ActiveInd]
          ,[LastUpdateUserNm]
          ,[LastUpdateUserDtm]
          ,[LastUpdateSystemUserDtm]
          ,[LastUpdateSystemUserNm]
          ,[CreateDtm]
          ,[CreateUserNm]
          ,[IOTGCustomerInd]
          ,[ExpectedBillingRegionCd]
          ,[RebateSubCustomer]
          ,[TDFAlignmentCustomerGroupNm]
          ,[CustomerGroupRebateCustomerInd]
          ,[VistexCustomerInd]
          ,[SubCustomerRebateCustomerInd]
          ,[IFSGroupNm]
          ,[NPGGroupNm]
          ,[CGEthernetAdapterGroupNm]
          ,[CGEthernetControllerGroupNm]
          ,[AXGClientDiscreteGraphicsGroupNm]
          ,[NPGWirelessAccessNetworkGroupNm]
          ,[AXGDataCenterDiscreteGraphicsGroupNm]
          ,[CreatedBy]
          ,[CreatedOn]
        FROM dbo.StgCustomerHierarchy) AS SOURCE
        ON SOURCE.[CustomerNodeId] = TARGET.[CustomerNodeId]
        WHEN NOT MATCHED BY TARGET THEN
        INSERT ( [CustomerNodeId]
              ,[CustomerGroup]
              ,[SubCustomer]
              ,[CustomerAllocationGroupCd]
              ,[PartyID]
              ,[HostedRegion]
              ,[CustomerType]
              ,[CCGCPUNotebookGroupNm]
              ,[CCGCPUDesktopGroupNm]
              ,[CCGChipsetGroupNm]
              ,[CCGDesktopWorkstationGroupNm]
              ,[CCGMobileCommGrp]
              ,[CCGWifiGrp]
              ,[CCGConnectivityGrp]
              ,[DCGGrp]
              ,[DCGOptaneGrp]
              ,[IOTGGrp]
              ,[CustomerAllocationGroupNm]
              ,[SourceSystem]
              ,[SMGSalesRollup]
              ,[DistributionChannelNm]
              ,[DistributionChannelCd]
              ,[SalesOfficeCd]
              ,[SalesOfficeNm]
              ,[GeographyCd]
              ,[SalesGroupCd]
              ,[SalesGroupNm]
              ,[CustomerNm]
              ,[CustomerClassificationCd]
              ,[CustomerClassificationNm]
              ,[CustomerCountryCd]
              ,[CustomerCountryNm]
              ,[CustomerAggregationLevelOneNm]
              ,[CustomerAggregationLevelTwoNm]
              ,[CustomerAggregationLevelThreeNm]
              ,[SalesOrganizationCd]
              ,[PriceCustomerGroupCd]
              ,[BusinessNameTypeCd]
              ,[BusinessNameTypeNm]
              ,[BusinessNameTypeDsc]
              ,[CustomerBusinessPartyIdTypeNm]
              ,[DirectCustomerRoleCd]
              ,[CustomerCentralArchivalDeleteBlockCd]
              ,[IntelProductGroupCd]
              ,[IntelUltimateBusinessPartyId]
              ,[CustomerCentralOrderBlockCd]
              ,[CustomerCentralBillingBlockCd]
              ,[CustomerCentralDeliveryBlockCd]
              ,[CustomerBusinessRoutingCd]
              ,[CustomerBusinessRoutingNm]
              ,[CustomerCentralDeleteBlockCd]
              ,[HierarchyLevelId]
              ,[SourceName]
              ,[AllCustomerIdentifier]
              ,[SalesAndOperationsPlanningCustomerGroupId]
              ,[SalesAndOperationsPlanningSubCustomerId]
              ,[SalesAndOperationsPlanningCustomerAllocationGroupId]
              ,[SalesAndOperationsPlanningPartyId]
              ,[CustomerBusinessOrganizationNm]
              ,[CustomerSupplyAllocationClassificationCd]
              ,[CustomerSupplyAllocationClassificationNm]
              ,[PartnerCustomerBusinessPartyId]
              ,[CustomerRelationshipFunctionalRoleCd]
              ,[CustomerRelationshipFunctionalRoleNm]
              ,[ActiveInd]
              ,[LastUpdateUserNm]
              ,[LastUpdateUserDtm]
              ,[LastUpdateSystemUserDtm]
              ,[LastUpdateSystemUserNm]
              ,[CreateDtm]
              ,[CreateUserNm]
              ,[IOTGCustomerInd]
              ,[ExpectedBillingRegionCd]
              ,[RebateSubCustomer]
              ,[TDFAlignmentCustomerGroupNm]
              ,[CustomerGroupRebateCustomerInd]
              ,[VistexCustomerInd]
              ,[SubCustomerRebateCustomerInd]
              ,[IFSGroupNm]
              ,[NPGGroupNm]
              ,[CGEthernetAdapterGroupNm]
              ,[CGEthernetControllerGroupNm]
              ,[AXGClientDiscreteGraphicsGroupNm]
              ,[NPGWirelessAccessNetworkGroupNm]
              ,[AXGDataCenterDiscreteGraphicsGroupNm])
        VALUES (
              SOURCE.[CustomerNodeId]
            ,SOURCE.[CustomerGroup]
            ,SOURCE.[SubCustomer]
            ,SOURCE.[CustomerAllocationGroupCd]
            ,SOURCE.[PartyID]
            ,SOURCE.[HostedRegion]
            ,SOURCE.[CustomerType]
            ,SOURCE.[CCGCPUNotebookGroupNm]
            ,SOURCE.[CCGCPUDesktopGroupNm]
            ,SOURCE.[CCGChipsetGroupNm]
            ,SOURCE.[CCGDesktopWorkstationGroupNm]
            ,SOURCE.[CCGMobileCommGrp]
            ,SOURCE.[CCGWifiGrp]
            ,SOURCE.[CCGConnectivityGrp]
            ,SOURCE.[DCGGrp]
            ,SOURCE.[DCGOptaneGrp]
            ,SOURCE.[IOTGGrp]
            ,SOURCE.[CustomerAllocationGroupNm]
            ,SOURCE.[SourceSystem]
            ,SOURCE.[SMGSalesRollup]
            ,SOURCE.[DistributionChannelNm]
            ,SOURCE.[DistributionChannelCd]
            ,SOURCE.[SalesOfficeCd]
            ,SOURCE.[SalesOfficeNm]
            ,SOURCE.[GeographyCd]
            ,SOURCE.[SalesGroupCd]
            ,SOURCE.[SalesGroupNm]
            ,SOURCE.[CustomerNm]
            ,SOURCE.[CustomerClassificationCd]
            ,SOURCE.[CustomerClassificationNm]
            ,SOURCE.[CustomerCountryCd]
            ,SOURCE.[CustomerCountryNm]
            ,SOURCE.[CustomerAggregationLevelOneNm]
            ,SOURCE.[CustomerAggregationLevelTwoNm]
            ,SOURCE.[CustomerAggregationLevelThreeNm]
            ,SOURCE.[SalesOrganizationCd]
            ,SOURCE.[PriceCustomerGroupCd]
            ,SOURCE.[BusinessNameTypeCd]
            ,SOURCE.[BusinessNameTypeNm]
            ,SOURCE.[BusinessNameTypeDsc]
            ,SOURCE.[CustomerBusinessPartyIdTypeNm]
            ,SOURCE.[DirectCustomerRoleCd]
            ,SOURCE.[CustomerCentralArchivalDeleteBlockCd]
            ,SOURCE.[IntelProductGroupCd]
            ,SOURCE.[IntelUltimateBusinessPartyId]
            ,SOURCE.[CustomerCentralOrderBlockCd]
            ,SOURCE.[CustomerCentralBillingBlockCd]
            ,SOURCE.[CustomerCentralDeliveryBlockCd]
            ,SOURCE.[CustomerBusinessRoutingCd]
            ,SOURCE.[CustomerBusinessRoutingNm]
            ,SOURCE.[CustomerCentralDeleteBlockCd]
            ,SOURCE.[HierarchyLevelId]
            ,SOURCE.[SourceName]
            ,SOURCE.[AllCustomerIdentifier]
            ,SOURCE.[SalesAndOperationsPlanningCustomerGroupId]
            ,SOURCE.[SalesAndOperationsPlanningSubCustomerId]
            ,SOURCE.[SalesAndOperationsPlanningCustomerAllocationGroupId]
            ,SOURCE.[SalesAndOperationsPlanningPartyId]
            ,SOURCE.[CustomerBusinessOrganizationNm]
            ,SOURCE.[CustomerSupplyAllocationClassificationCd]
            ,SOURCE.[CustomerSupplyAllocationClassificationNm]
            ,SOURCE.[PartnerCustomerBusinessPartyId]
            ,SOURCE.[CustomerRelationshipFunctionalRoleCd]
            ,SOURCE.[CustomerRelationshipFunctionalRoleNm]
            ,SOURCE.[ActiveInd]
            ,SOURCE.[LastUpdateUserNm]
            ,SOURCE.[LastUpdateUserDtm]
            ,SOURCE.[LastUpdateSystemUserDtm]
            ,SOURCE.[LastUpdateSystemUserNm]
            ,SOURCE.[CreateDtm]
            ,SOURCE.[CreateUserNm]
            ,SOURCE.[IOTGCustomerInd]
            ,SOURCE.[ExpectedBillingRegionCd]
            ,SOURCE.[RebateSubCustomer]
            ,SOURCE.[TDFAlignmentCustomerGroupNm]
            ,SOURCE.[CustomerGroupRebateCustomerInd]
            ,SOURCE.[VistexCustomerInd]
            ,SOURCE.[SubCustomerRebateCustomerInd]
            ,SOURCE.[IFSGroupNm]
            ,SOURCE.[NPGGroupNm]
            ,SOURCE.[CGEthernetAdapterGroupNm]
            ,SOURCE.[CGEthernetControllerGroupNm]
            ,SOURCE.[AXGClientDiscreteGraphicsGroupNm]
            ,SOURCE.[NPGWirelessAccessNetworkGroupNm]
            ,SOURCE.[AXGDataCenterDiscreteGraphicsGroupNm])
        WHEN MATCHED THEN 
        UPDATE
            SET
                TARGET.[CustomerGroup] = SOURCE.[CustomerGroup]
                ,TARGET.[SubCustomer] = SOURCE.[SubCustomer]
                ,TARGET.[CustomerAllocationGroupCd] = SOURCE.[CustomerAllocationGroupCd]
                ,TARGET.[PartyID] = SOURCE.[PartyID]
                ,TARGET.[HostedRegion] = SOURCE.[HostedRegion]
                ,TARGET.[CustomerType] = SOURCE.[CustomerType]
                ,TARGET.[CCGCPUNotebookGroupNm] = SOURCE.[CCGCPUNotebookGroupNm]
                ,TARGET.[CCGCPUDesktopGroupNm] = SOURCE.[CCGCPUDesktopGroupNm]
                ,TARGET.[CCGChipsetGroupNm] = SOURCE.[CCGChipsetGroupNm]
                ,TARGET.[CCGDesktopWorkstationGroupNm] = SOURCE.[CCGDesktopWorkstationGroupNm]
                ,TARGET.[CCGMobileCommGrp] = SOURCE.[CCGMobileCommGrp]
                ,TARGET.[CCGWifiGrp] = SOURCE.[CCGWifiGrp]
                ,TARGET.[CCGConnectivityGrp] = SOURCE.[CCGConnectivityGrp]
                ,TARGET.[DCGGrp] = SOURCE.[DCGGrp]
                ,TARGET.[DCGOptaneGrp] = SOURCE.[DCGOptaneGrp]
                ,TARGET.[IOTGGrp] = SOURCE.[IOTGGrp]
                ,TARGET.[CustomerAllocationGroupNm] = SOURCE.[CustomerAllocationGroupNm]
                ,TARGET.[SourceSystem] = SOURCE.[SourceSystem]
                ,TARGET.[SMGSalesRollup] = SOURCE.[SMGSalesRollup]
                ,TARGET.[DistributionChannelNm] = SOURCE.[DistributionChannelNm]
                ,TARGET.[DistributionChannelCd] = SOURCE.[DistributionChannelCd]
                ,TARGET.[SalesOfficeCd] = SOURCE.[SalesOfficeCd]
                ,TARGET.[SalesOfficeNm] = SOURCE.[SalesOfficeNm]
                ,TARGET.[GeographyCd] = SOURCE.[GeographyCd]
                ,TARGET.[SalesGroupCd] = SOURCE.[SalesGroupCd]
                ,TARGET.[SalesGroupNm] = SOURCE.[SalesGroupNm]
                ,TARGET.[CustomerNm] = SOURCE.[CustomerNm]
                ,TARGET.[CustomerClassificationCd] = SOURCE.[CustomerClassificationCd]
                ,TARGET.[CustomerClassificationNm] = SOURCE.[CustomerClassificationNm]
                ,TARGET.[CustomerCountryCd] = SOURCE.[CustomerCountryCd]
                ,TARGET.[CustomerCountryNm] = SOURCE.[CustomerCountryNm]
                ,TARGET.[CustomerAggregationLevelOneNm] = SOURCE.[CustomerAggregationLevelOneNm]
                ,TARGET.[CustomerAggregationLevelTwoNm] = SOURCE.[CustomerAggregationLevelTwoNm]
                ,TARGET.[CustomerAggregationLevelThreeNm] = SOURCE.[CustomerAggregationLevelThreeNm]
                ,TARGET.[SalesOrganizationCd] = SOURCE.[SalesOrganizationCd]
                ,TARGET.[PriceCustomerGroupCd] = SOURCE.[PriceCustomerGroupCd]
                ,TARGET.[BusinessNameTypeCd] = SOURCE.[BusinessNameTypeCd]
                ,TARGET.[BusinessNameTypeNm] = SOURCE.[BusinessNameTypeNm]
                ,TARGET.[BusinessNameTypeDsc] = SOURCE.[BusinessNameTypeDsc]
                ,TARGET.[CustomerBusinessPartyIdTypeNm] = SOURCE.[CustomerBusinessPartyIdTypeNm]
                ,TARGET.[DirectCustomerRoleCd] = SOURCE.[DirectCustomerRoleCd]
                ,TARGET.[CustomerCentralArchivalDeleteBlockCd] = SOURCE.[CustomerCentralArchivalDeleteBlockCd]
                ,TARGET.[IntelProductGroupCd] = SOURCE.[IntelProductGroupCd]
                ,TARGET.[IntelUltimateBusinessPartyId] = SOURCE.[IntelUltimateBusinessPartyId]
                ,TARGET.[CustomerCentralOrderBlockCd] = SOURCE.[CustomerCentralOrderBlockCd]
                ,TARGET.[CustomerCentralBillingBlockCd] = SOURCE.[CustomerCentralBillingBlockCd]
                ,TARGET.[CustomerCentralDeliveryBlockCd] = SOURCE.[CustomerCentralDeliveryBlockCd]
                ,TARGET.[CustomerBusinessRoutingCd] = SOURCE.[CustomerBusinessRoutingCd]
                ,TARGET.[CustomerBusinessRoutingNm] = SOURCE.[CustomerBusinessRoutingNm]
                ,TARGET.[CustomerCentralDeleteBlockCd] = SOURCE.[CustomerCentralDeleteBlockCd]
                ,TARGET.[HierarchyLevelId] = SOURCE.[HierarchyLevelId]
                ,TARGET.[SourceName] = SOURCE.[SourceName]
                ,TARGET.[AllCustomerIdentifier] = SOURCE.[AllCustomerIdentifier]
                ,TARGET.[SalesAndOperationsPlanningCustomerGroupId] = SOURCE.[SalesAndOperationsPlanningCustomerGroupId]
                ,TARGET.[SalesAndOperationsPlanningSubCustomerId] = SOURCE.[SalesAndOperationsPlanningSubCustomerId]
                ,TARGET.[SalesAndOperationsPlanningCustomerAllocationGroupId] = SOURCE.[SalesAndOperationsPlanningCustomerAllocationGroupId]
                ,TARGET.[SalesAndOperationsPlanningPartyId] = SOURCE.[SalesAndOperationsPlanningPartyId]
                ,TARGET.[CustomerBusinessOrganizationNm] = SOURCE.[CustomerBusinessOrganizationNm]
                ,TARGET.[CustomerSupplyAllocationClassificationCd] = SOURCE.[CustomerSupplyAllocationClassificationCd]
                ,TARGET.[CustomerSupplyAllocationClassificationNm] = SOURCE.[CustomerSupplyAllocationClassificationNm]
                ,TARGET.[PartnerCustomerBusinessPartyId] = SOURCE.[PartnerCustomerBusinessPartyId]
                ,TARGET.[CustomerRelationshipFunctionalRoleCd] = SOURCE.[CustomerRelationshipFunctionalRoleCd]
                ,TARGET.[CustomerRelationshipFunctionalRoleNm] = SOURCE.[CustomerRelationshipFunctionalRoleNm]
                ,TARGET.[ActiveInd] = SOURCE.[ActiveInd]
                ,TARGET.[LastUpdateUserNm] = SOURCE.[LastUpdateUserNm]
                ,TARGET.[LastUpdateUserDtm] = SOURCE.[LastUpdateUserDtm]
                ,TARGET.[LastUpdateSystemUserDtm] = SOURCE.[LastUpdateSystemUserDtm]
                ,TARGET.[LastUpdateSystemUserNm] = SOURCE.[LastUpdateSystemUserNm]
                ,TARGET.[CreateDtm] = SOURCE.[CreateDtm]
                ,TARGET.[CreateUserNm] = SOURCE.[CreateUserNm]
                ,TARGET.[IOTGCustomerInd] = SOURCE.[IOTGCustomerInd]
                ,TARGET.[ExpectedBillingRegionCd] = SOURCE.[ExpectedBillingRegionCd]
                ,TARGET.[RebateSubCustomer] = SOURCE.[RebateSubCustomer]
                ,TARGET.[TDFAlignmentCustomerGroupNm] = SOURCE.[TDFAlignmentCustomerGroupNm]
                ,TARGET.[CustomerGroupRebateCustomerInd] = SOURCE.[CustomerGroupRebateCustomerInd]
                ,TARGET.[VistexCustomerInd] = SOURCE.[VistexCustomerInd]
                ,TARGET.[SubCustomerRebateCustomerInd] = SOURCE.[SubCustomerRebateCustomerInd]
                ,TARGET.[IFSGroupNm] = SOURCE.[IFSGroupNm]
                ,TARGET.[NPGGroupNm] = SOURCE.[NPGGroupNm]
                ,TARGET.[CGEthernetAdapterGroupNm] = SOURCE.[CGEthernetAdapterGroupNm]
                ,TARGET.[CGEthernetControllerGroupNm] = SOURCE.[CGEthernetControllerGroupNm]
                ,TARGET.[AXGClientDiscreteGraphicsGroupNm] = SOURCE.[AXGClientDiscreteGraphicsGroupNm]
                ,TARGET.[NPGWirelessAccessNetworkGroupNm] = SOURCE.[NPGWirelessAccessNetworkGroupNm]
                ,TARGET.[AXGDataCenterDiscreteGraphicsGroupNm] = SOURCE.[AXGDataCenterDiscreteGraphicsGroupNm]
                ,TARGET.[CreatedOn] = SOURCE.[CreatedOn]
                ,TARGET.[CreatedBy] = SOURCE.[CreatedBy]
        WHEN NOT MATCHED BY SOURCE THEN 
        UPDATE
            SET 
                TARGET.[ActiveInd] = 'N';
        
        --Logging End

        EXEC dbo.UspAddApplicationLog 'Database', 'Info', 'LoadCustomerHierarchy', 'UspLoadCustomerHierarchy','Load daily data from Market Segment', 'END', NULL, @BatchId
        
        --Send sucess email to MPS Recon support PDL
        --EXEC dbo.UspMPSReconSendEmail @EmailBody=@EmailMessage,@EmailSubject= 'LoadCustomerHierarchy Successful'

    END TRY
    BEGIN CATCH 
        
        --Send failure email to MPS Recon support PDL 
        SET @Prog = ERROR_PROCEDURE();
        SET @EmailMessage='LoadCustomerHierarchy failed '+' at line : '+ CONVERT(varchar(10),(ERROR_LINE()))+ '<BR>' +'Error in : '+@Prog+ '<BR>'+ 'Error Message : ' + ERROR_MESSAGE()

        EXEC dbo.UspMPSReconSendEmail @EmailBody=@EmailMessage,@EmailSubject='LoadCustomerHierarchy Failed'

        --Add Entry in Log Table
        DECLARE @ErrorMsg VARCHAR(MAX)=ERROR_MESSAGE()
        EXEC dbo.UspAddApplicationLog 'Database', 'Info', 'LoadCustomerHierarchy','UspLoadCustomerHierarchy', 'Load daily data from Market Segment','ERROR', @ErrorMsg, @BatchId

        RAISERROR(@ErrorMsg, 16, 1)
    END CATCH
    
    SET NOCOUNT OFF
END
